### ISSUE TITLE
計算結果が正しく表示されない

### ISSUE THREAD

**Issue by TsukamotoShunya** [TsukamotoShunya/git-boot-camp-20181130-work1#1]
## 操作手順
プルダウンで「÷」を選択。
ボタン「=」を押下。
計算結果が「×」の物になっている。

## 本来の想定
プルダウンで「÷」を選択。
ボタン「=」を押下。
計算結果が「÷」の物になっている。

## 操作環境
* OS Mac
* ブラウザ Chrome

**Comment by yuki-sato-mg** [comment]
修正できてえらい
